import { Alg } from "./types";

export const algList: Alg[] = [
  { name: "AH", alg: "U'/R D' R'" },
{ name: "HA", alg: "U/R D' R'" },
{ name: "AL", alg: "D': U'/R D' R'" },
{ name: "LA", alg: "D': U/R D' R'" },
{ name: "EI", alg: "l': U/R D' R'" },
{ name: "IE", alg: "l': U'/R D' R'" },
{ name: "NS", alg: "U' R': U'/R D' R'" },
{ name: "SN", alg: "U' R': U/R D' R'" },
{ name: "NO", alg: "U' D R': U'/R D' R'" },
{ name: "ON", alg: "U' D R': U/R D' R'" },
{ name: "VX", alg: "R U' R': U/R D' R'" },
{ name: "XV", alg: "R U' R': U'/R D' R'" },

//   { name: "DV", alg: "R' D R U' R D' R', U'" },
//   { name: "VD", alg: "U', R' D R U' R D' R' " },
//   { name: "BV", alg: "R' D R U' R D' R', U" },
//   { name: "VB", alg: "U, R' D R U' R D' R' " },
//   { name: "WP", alg: "R: R' D R U' R D' R', U" },
//   { name: "PW", alg: "R: U, R' D R U' R D' R'" },

  { name: "RS", alg: "U' R' U': R D' R', U'" },
{ name: "SR", alg: "U' R' U2: R D' R', U" },
{ name: "KW", alg: "U R D': U', R' D R" },
{ name: "WK", alg: "U R D': R' D R, U'" },
{ name: "DX", alg: "R' D' R: R U' R', D" },
{ name: "XD", alg: "R' D' R: D, R U' R'" },
{ name: "NR", alg: "U R: U2, R D R'" },
{ name: "RN", alg: "U R: R D R', U2" },
{ name: "DN", alg: "U' R': U2, R' D' R" },
{ name: "ND", alg: "U' R': R' D' R, U2" },
{ name: "LW", alg: "D R: R D' R', U'" },
{ name: "WL", alg: "D R: U', R D' R'" },
{ name: "PX", alg: "R: R D' R', U'" },
{ name: "XP", alg: "R: U', R D' R'" },
{ name: "FU", alg: "U' R' U: R U' R', D" },
{ name: "UF", alg: "U' R' U: D, R U' R'" },
{ name: "KQ", alg: "D' R' U: R U' R', D" },
{ name: "QK", alg: "D' R' U: D, R U' R'" },
{ name: "KX", alg: "R' D' R: R U R', D" },
{ name: "XK", alg: "R' D' R: D, R U R'" },
{ name: "DQ", alg: "R' D': U', R' D R" },
{ name: "QD", alg: "R' D': R' D R, U'" },
{ name: "LV", alg: "R U' R': R' D R, U2" },
{ name: "VL", alg: "R U' R': U2, R' D R" },
{ name: "HK", alg: "U R U': R D' R', U'" },
{ name: "KH", alg: "U R U': U', R D' R'" },

];